// Friendly 1:1 mapping of SDL2 key codes to Thundershock key event values.
//
// There is definitely optimization needed hete.
//
// I've never HEARD of some of these keys. Whoever has a number pad
// with hexadecimal digits on it please text "ritchie" to +1 (555) 867-5309
// and nobody will answer because you aren't real.

namespace Thundershock.Core.Input
{
	public enum Keys
	{
		None = 0,
		Return = '\r',
		Enter = Return,
		Escape = 27, // '\033'
		Backspace = '\b',
		Tab = '\t',
		Space = ' ',
		Exclaim = '!',
		Quote = '"',
		Hash = '#',
		Percent = '%',
		Dollar = '$',
		Ampersand = '&',
		Apostrophe = '\'',
		OpenParenthesis = '(',
		CloseParanthesis = ')',
		Asterisk = '*',
		Plus = '+',
		Comma = ',',
		Minus = '-',
		Period = '.',
		Slash = '/',
		D0 = '0',
		D1 = '1',
		D2 = '2',
		D3 = '3',
		D4 = '4',
		D5 = '5',
		D6 = '6',
		D7 = '7',
		D8 = '8',
		D9 = '9',
		Colon = ':',
		Semicolon = ';',
		LessThan = '<',
		Equal = '=',
		GreaterThan = '>',
		Question = '?',
		At = '@',

		/*
		Skip uppercase letters
		*/
		OpenBracket = '[',
		Backslash = '\\',
		CloseBracket = ']',
		Caret = '^',
		Underscore = '_',
		BackQuote = '`',
		A = 'a',
		B = 'b',
		C = 'c',
		D = 'd',
		E = 'e',
		F = 'f',
		G = 'g',
		H = 'h',
		I = 'i',
		J = 'j',
		K = 'k',
		L = 'l',
		M = 'm',
		N = 'n',
		O = 'o',
		P = 'p',
		Q = 'q',
		R = 'r',
		S = 's',
		T = 't',
		U = 'u',
		V = 'v',
		W = 'w',
		X = 'x',
		Y = 'y',
		Z = 'z',

		ScancodeBit = (1 << 30),
		
		SDLK_CAPSLOCK = (int) 57 | ScancodeBit,

		F1 = (int) 58 | ScancodeBit,
		F2 = (int) 59 | ScancodeBit,
		F3 = (int) 60 | ScancodeBit,
		F4 = (int) 61 | ScancodeBit,
		F5 = (int) 62 | ScancodeBit,
		F6 = (int) 63 | ScancodeBit,
		F7 = (int) 64 | ScancodeBit,
		F8 = (int) 65 | ScancodeBit,
		F9 = (int) 66 | ScancodeBit,
		F10 = (int) 67 | ScancodeBit,
		F11 = (int) 68 | ScancodeBit,
		F12 = (int) 69 | ScancodeBit,

		PrintScreen = (int) 70 | ScancodeBit,
		CapsLock = (int) 71 | ScancodeBit,
		Pause = (int) 72 | ScancodeBit,
		Insert = (int) 73 | ScancodeBit,
		Home = (int) 74 | ScancodeBit,
		PageUp = (int) 75 | ScancodeBit,
		Delete = 127,
		End = (int) 77 | ScancodeBit,
		PageDown = (int) 78 | ScancodeBit,
		Right = (int) 79 | ScancodeBit,
		Left = (int) 80 | ScancodeBit,
		Down = (int) 81 | ScancodeBit,
		Up = (int) 82 | ScancodeBit,

		NumLockClear = (int) 83 | ScancodeBit,
		OemDivide = (int) 84 | ScancodeBit,
		OemMultiply = (int) 85 | ScancodeBit,
		OemMinus = (int) 86 | ScancodeBit,
		OemPlus = (int) 87 | ScancodeBit,
		OemEnter = (int) 88 | ScancodeBit,
		Num1 = (int) 89 | ScancodeBit,
		Num2 = (int) 90 | ScancodeBit,
		Num3 = (int) 91 | ScancodeBit,
		Num4 = (int) 92 | ScancodeBit,
		Num5 = (int) 93 | ScancodeBit,
		Num6 = (int) 94 | ScancodeBit,
		Num7 = (int) 95 | ScancodeBit,
		Num8 = (int) 96 | ScancodeBit,
		Num9 = (int) 97 | ScancodeBit,
		Num0 = (int) 98 | ScancodeBit,
		OemPeriod = (int) 99 | ScancodeBit,

		OemApplication = (int) 101 | ScancodeBit,
		OemPower = (int) 102 | ScancodeBit,
		OemEqual = (int) 103 | ScancodeBit,
		F13 = (int) 104 | ScancodeBit,
		F14 = (int) 105 | ScancodeBit,
		F15 = (int) 106 | ScancodeBit,
		F16 = (int) 107 | ScancodeBit,
		F17 = (int) 108 | ScancodeBit,
		F18 = (int) 109 | ScancodeBit,
		F19 = (int) 110 | ScancodeBit,
		F20 = (int) 111 | ScancodeBit,
		F21 = (int) 112 | ScancodeBit,
		F22 = (int) 113 | ScancodeBit,
		F23 = (int) 114 | ScancodeBit,
		F24 = (int) 115 | ScancodeBit,
		
		OemExecute = (int) 116 | ScancodeBit,
		OemHelp = (int) 117 | ScancodeBit,
		OemMenu = (int) 118 | ScancodeBit,
		OemSelect = (int) 119 | ScancodeBit,
		OemStop = (int) 120 | ScancodeBit,
		OemAgain = (int) 121 | ScancodeBit,
		OemUndo = (int) 122 | ScancodeBit,
		OemCut = (int) 123 | ScancodeBit,
		OemCopy = (int) 124 | ScancodeBit,
		OemPaste = (int) 125 | ScancodeBit,
		OemFind = (int) 126 | ScancodeBit,
		OemMute = (int) 127 | ScancodeBit,
		OemVolumeUp = (int) 128 | ScancodeBit,
		OemVolumeDown = (int) 129 | ScancodeBit,
		
		OemComma = (int) 133 | ScancodeBit,

		EqualsAs400 = (int) 134 | ScancodeBit,

		AltErase = (int) 153 | ScancodeBit,
		SysReq = (int) 154 | ScancodeBit,
		Cancel = (int) 155 | ScancodeBit,
		Clear = (int) 156 | ScancodeBit,
		Print = (int) 157 | ScancodeBit,
		OemReturn = (int) 158 | ScancodeBit,
		Separator = (int) 159 | ScancodeBit,
		Out = (int) 160 | ScancodeBit,
		Oper = (int) 161 | ScancodeBit,
		ClearAgain = (int) 162 | ScancodeBit,
		CrSel = (int) 163 | ScancodeBit,
		ExSel = (int) 164 | ScancodeBit,

		// what????
		Num00 = (int) 176 | ScancodeBit,
		Num000 = (int) 177 | ScancodeBit,
		ThousandsSeparator = (int) 178 | ScancodeBit,
		DecimalSeparator = (int) 179 | ScancodeBit,
		CurrencyUnit = (int) 180 | ScancodeBit,
		CurrencySubunit = (int) 181 | ScancodeBit,
		
		OemOpenParenthesis = (int) 182 | ScancodeBit,
		OemCloseParenthesis = (int) 183 | ScancodeBit,
		OemOpenBrace = (int) 184 | ScancodeBit,
		OemCloseBrace = (int) 185 | ScancodeBit,
		OemTab = (int) 186 | ScancodeBit,
		OemBackspace = (int) 187 | ScancodeBit,
		Oem10 = (int) 188 | ScancodeBit,
		Oem11 = (int) 189 | ScancodeBit,
		Oem12 = (int) 190 | ScancodeBit,
		Oem13 = (int) 191 | ScancodeBit,
		Oem14 = (int) 192 | ScancodeBit,
		Oem15 = (int) 193 | ScancodeBit,
		OemXor = (int) 194 | ScancodeBit,
		OemExponent = (int) 195 | ScancodeBit,
		OemPercent = (int) 196 | ScancodeBit,
		OemLessThan = (int) 197 | ScancodeBit,
		OemGreaterThan = (int) 198 | ScancodeBit,
		OemAmpersand = (int) 199 | ScancodeBit,

		/* TODO
		SDLK_KP_DBLAMPERSAND =
			(int) SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND | ScancodeBit,

		SDLK_KP_VERTICALBAR =
			(int) SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR | ScancodeBit,

		SDLK_KP_DBLVERTICALBAR =
			(int) SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR | ScancodeBit,
		SDLK_KP_COLON = (int) SDL_Scancode.SDL_SCANCODE_KP_COLON | ScancodeBit,
		SDLK_KP_HASH = (int) SDL_Scancode.SDL_SCANCODE_KP_HASH | ScancodeBit,
		SDLK_KP_SPACE = (int) SDL_Scancode.SDL_SCANCODE_KP_SPACE | ScancodeBit,
		SDLK_KP_AT = (int) SDL_Scancode.SDL_SCANCODE_KP_AT | ScancodeBit,
		SDLK_KP_EXCLAM = (int) SDL_Scancode.SDL_SCANCODE_KP_EXCLAM | ScancodeBit,
		SDLK_KP_MEMSTORE = (int) SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE | ScancodeBit,
		SDLK_KP_MEMRECALL = (int) SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL | ScancodeBit,
		SDLK_KP_MEMCLEAR = (int) SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR | ScancodeBit,
		SDLK_KP_MEMADD = (int) SDL_Scancode.SDL_SCANCODE_KP_MEMADD | ScancodeBit,

		SDLK_KP_MEMSUBTRACT =
			(int) SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT | ScancodeBit,

		SDLK_KP_MEMMULTIPLY =
			(int) SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY | ScancodeBit,
		SDLK_KP_MEMDIVIDE = (int) SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE | ScancodeBit,
		SDLK_KP_PLUSMINUS = (int) SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS | ScancodeBit,
		SDLK_KP_CLEAR = (int) SDL_Scancode.SDL_SCANCODE_KP_CLEAR | ScancodeBit,
		SDLK_KP_CLEARENTRY = (int) SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY | ScancodeBit,
		SDLK_KP_BINARY = (int) SDL_Scancode.SDL_SCANCODE_KP_BINARY | ScancodeBit,
		SDLK_KP_OCTAL = (int) SDL_Scancode.SDL_SCANCODE_KP_OCTAL | ScancodeBit,
		SDLK_KP_DECIMAL = (int) SDL_Scancode.SDL_SCANCODE_KP_DECIMAL | ScancodeBit,

		SDLK_KP_HEXADECIMAL =
			(int) SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL | ScancodeBit,

		SDLK_LCTRL = (int) SDL_Scancode.SDL_SCANCODE_LCTRL | ScancodeBit,
		SDLK_LSHIFT = (int) SDL_Scancode.SDL_SCANCODE_LSHIFT | ScancodeBit,
		SDLK_LALT = (int) SDL_Scancode.SDL_SCANCODE_LALT | ScancodeBit,
		SDLK_LGUI = (int) SDL_Scancode.SDL_SCANCODE_LGUI | ScancodeBit,
		SDLK_RCTRL = (int) SDL_Scancode.SDL_SCANCODE_RCTRL | ScancodeBit,
		SDLK_RSHIFT = (int) SDL_Scancode.SDL_SCANCODE_RSHIFT | ScancodeBit,
		SDLK_RALT = (int) SDL_Scancode.SDL_SCANCODE_RALT | ScancodeBit,
		SDLK_RGUI = (int) SDL_Scancode.SDL_SCANCODE_RGUI | ScancodeBit,

		SDLK_MODE = (int) SDL_Scancode.SDL_SCANCODE_MODE | ScancodeBit,

		SDLK_AUDIONEXT = (int) SDL_Scancode.SDL_SCANCODE_AUDIONEXT | ScancodeBit,
		SDLK_AUDIOPREV = (int) SDL_Scancode.SDL_SCANCODE_AUDIOPREV | ScancodeBit,
		SDLK_AUDIOSTOP = (int) SDL_Scancode.SDL_SCANCODE_AUDIOSTOP | ScancodeBit,
		SDLK_AUDIOPLAY = (int) SDL_Scancode.SDL_SCANCODE_AUDIOPLAY | ScancodeBit,
		SDLK_AUDIOMUTE = (int) SDL_Scancode.SDL_SCANCODE_AUDIOMUTE | ScancodeBit,
		SDLK_MEDIASELECT = (int) SDL_Scancode.SDL_SCANCODE_MEDIASELECT | ScancodeBit,
		SDLK_WWW = (int) SDL_Scancode.SDL_SCANCODE_WWW | ScancodeBit,
		SDLK_MAIL = (int) SDL_Scancode.SDL_SCANCODE_MAIL | ScancodeBit,
		SDLK_CALCULATOR = (int) SDL_Scancode.SDL_SCANCODE_CALCULATOR | ScancodeBit,
		SDLK_COMPUTER = (int) SDL_Scancode.SDL_SCANCODE_COMPUTER | ScancodeBit,
		SDLK_AC_SEARCH = (int) SDL_Scancode.SDL_SCANCODE_AC_SEARCH | ScancodeBit,
		SDLK_AC_HOME = (int) SDL_Scancode.SDL_SCANCODE_AC_HOME | ScancodeBit,
		SDLK_AC_BACK = (int) SDL_Scancode.SDL_SCANCODE_AC_BACK | ScancodeBit,
		SDLK_AC_FORWARD = (int) SDL_Scancode.SDL_SCANCODE_AC_FORWARD | ScancodeBit,
		SDLK_AC_STOP = (int) SDL_Scancode.SDL_SCANCODE_AC_STOP | ScancodeBit,
		SDLK_AC_REFRESH = (int) SDL_Scancode.SDL_SCANCODE_AC_REFRESH | ScancodeBit,
		SDLK_AC_BOOKMARKS = (int) SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS | ScancodeBit,

		SDLK_BRIGHTNESSDOWN =
			(int) SDL_Scancode.SDL_SCANCODE_BRIGHTNESSDOWN | ScancodeBit,
		SDLK_BRIGHTNESSUP = (int) SDL_Scancode.SDL_SCANCODE_BRIGHTNESSUP | ScancodeBit,
		SDLK_DISPLAYSWITCH = (int) SDL_Scancode.SDL_SCANCODE_DISPLAYSWITCH | ScancodeBit,

		SDLK_KBDILLUMTOGGLE =
			(int) SDL_Scancode.SDL_SCANCODE_KBDILLUMTOGGLE | ScancodeBit,
		SDLK_KBDILLUMDOWN = (int) SDL_Scancode.SDL_SCANCODE_KBDILLUMDOWN | ScancodeBit,
		SDLK_KBDILLUMUP = (int) SDL_Scancode.SDL_SCANCODE_KBDILLUMUP | ScancodeBit,
		SDLK_EJECT = (int) SDL_Scancode.SDL_SCANCODE_EJECT | ScancodeBit,
		SDLK_SLEEP = (int) SDL_Scancode.SDL_SCANCODE_SLEEP | ScancodeBit,
		SDLK_APP1 = (int) SDL_Scancode.SDL_SCANCODE_APP1 | ScancodeBit,
		SDLK_APP2 = (int) SDL_Scancode.SDL_SCANCODE_APP2 | ScancodeBit,

		SDLK_AUDIOREWIND = (int) SDL_Scancode.SDL_SCANCODE_AUDIOREWIND | ScancodeBit,
		SDLK_AUDIOFASTFORWARD = (int) SDL_Scancode.SDL_SCANCODE_AUDIOFASTFORWARD | ScancodeBit */
	}
}