name: Documentation
on: [push]
jobs:
  docfx:
    runs-on: ubuntu-latest
    name: docfx job
    steps:
      - uses: actions/checkout@v1
      - uses: nikeee/docfx-action@v1.0.0
        name: "Build documentation"
        with:
          args: docfx.json
      - uses: burnett01/rsync-deployments@4.1
        name: "Deploy docs"
        with:
          switches: "-avzr --delete"
          path: "_site/"
          remote_path: /mnt/cruise_volume/docs/thundershock/
          remote_user: ghdeploy-thundershock
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_host: "${{ secrets.YOUNOGETIP }}"